version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: narcos_tacos_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: narcos
      POSTGRES_PASSWORD: narcos_dev
      POSTGRES_DB: narcos_tacos
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
